// Editorial layer — hand-written content per model id.
// Live facts (prices, context, capabilities, cached rates) come from
// models-live.js, generated by scripts/sync-models.mjs. Models without an
// editorial entry get a fallback card, so catalog additions never break the page.
// Quality scores & popularity (OR Rank) from https://theozard.com/models/text

const PROVIDER_NAMES = {
  "deepseek-ai": "DeepSeek",
  google: "Google",
  openai: "OpenAI",
  moonshotai: "Moonshot AI",
  qwen: "Qwen",
  "zai-org": "Z.ai",
  "motif-technologies": "Motif",
};

const EDITORIAL = {
  "deepseek-ai/deepseek-v4-flash": {
    quality: 67,          // Theozard "DeepSeek V4 Flash"
    popularity: 1,        // Theozard OR Rank
    description:
      "DeepSeek's fast, inexpensive workhorse. The best price-to-performance ratio on ai& and the most popular model on OpenRouter.",
    specialties: [
      "Cheapest output tokens on the platform ($0.25/1M)",
      "Full 1M-token context window",
      "#1 most popular model on OpenRouter",
    ],
    limitations: [
      "Text-only: no vision, video, or document input",
      "Quality score (67) trails the pro-tier models",
      "High-volume reasoning chains can add up — reasoning tokens bill as output",
    ],
  },
  "google/gemma-4-31b-it": {
    quality: null,
    popularity: null,
    description:
      "Google's multimodal Gemma — one of only two ai& models that accept video, alongside images and documents, at entry-level prices.",
    specialties: [
      "Video understanding plus vision + document input",
      "Cheapest cached input rate on the platform ($0.05/1M)",
      "Strong pick for multimodal pipelines on a budget",
    ],
    limitations: [
      "262K context — smaller than the 1M flagships",
      "Not yet listed on the Theozard leaderboard",
      "31B class: below flagship quality on complex reasoning",
    ],
  },
  "openai/gpt-oss-120b": {
    quality: null,
    popularity: null,
    description:
      "OpenAI's open-weight 120B model — solid reasoning and tool calling at the platform's cheapest input rate.",
    specialties: [
      "Cheapest input tokens on the platform ($0.15/1M)",
      "OpenAI open weights with reasoning + tool calling",
      "Good fit for agents with short, frequent calls",
    ],
    limitations: [
      "Smallest context window on ai& (131K)",
      "Text-only: no vision, video, or document input",
      "Not yet listed on the Theozard leaderboard",
    ],
  },
  "motif-technologies/motif-3": {
    quality: 75,          // Theozard "Motif 3"
    popularity: null,
    description:
      "Motif's general-purpose chat model — a mid-priced all-rounder with reasoning and tool calling.",
    specialties: [
      "Balanced mid-tier pricing ($0.50 / $2.00 per 1M)",
      "Reasoning + tool calling",
      "Respectable Theozard quality score (75)",
    ],
    limitations: [
      "262K context — no 1M option",
      "Text-only: no vision or document input",
      "Less established than the DeepSeek and GLM alternatives",
    ],
  },
  "deepseek-ai/deepseek-v4-pro": {
    quality: 72,          // Theozard "DeepSeek V4 Pro"
    popularity: 10,
    description:
      "DeepSeek's flagship open-weight model — a big quality step up from Flash, with the same 1M-token context window.",
    specialties: [
      "Full 1M-token context for long-document workloads",
      "Top-10 most popular model on OpenRouter",
      "Strong reasoning at roughly half the output price of GLM-5.2",
    ],
    limitations: [
      "Text-only: no vision, video, or document input",
      "~6.7x the input price of DeepSeek V4 Flash",
      "Quality (72) behind GLM-5.2 (83) and Kimi K3 (95)",
    ],
  },
  "qwen/qwen3.6-27b": {
    quality: null,
    popularity: null,
    description:
      "Qwen's compact 27B model — the cheapest multimodal option on ai&, accepting images, video, and documents.",
    specialties: [
      "Cheapest multimodal model: vision, video, and document input",
      "Low $0.20 cached input rate",
      "Good for evals and lightweight pipelines",
    ],
    limitations: [
      "27B class — below flagship quality on hard tasks",
      "Not listed on the Theozard leaderboard",
      "Was free until recently — now billed at $0.32 / $3.20 per 1M",
    ],
  },
  "moonshotai/kimi-k2.7-code": {
    quality: 68,          // Theozard "Kimi K2.7 Code"
    popularity: 76,
    description:
      "Moonshot's code-tuned Kimi — purpose-built for software engineering agents, with vision and document input for specs and screenshots.",
    specialties: [
      "Tuned for code generation, editing, and debugging agents",
      "Accepts image and document input (specs, diagrams, PDFs)",
      "Reasoning + tool calling for multi-step coding workflows",
    ],
    limitations: [
      "Premium output price ($3.50/1M) — long generations add up",
      "262K context, below the 1M flagships",
      "Code-tuning makes it narrower than general-purpose models",
    ],
  },
  "zai-org/glm-5.2": {
    quality: 83,          // Theozard "GLM-5.2"
    popularity: 8,
    description:
      "Z.ai's GLM-5.2 — the highest-quality text model under $1/1M input on ai&, paired with a full 1M-token context window.",
    specialties: [
      "Best quality per dollar on the platform (Theozard 83)",
      "1M-token context for huge documents and codebases",
      "#8 most popular model on OpenRouter",
    ],
    limitations: [
      "Mid-tier pricing: $1.00 / $4.00 per 1M tokens",
      "Text-only: no vision, video, or document input",
      "Kimi K3 outscores it (95) if you need the absolute best",
    ],
  },
  "moonshotai/kimi-k3": {
    quality: 95,          // Theozard "Kimi K3"
    popularity: 15,
    description:
      "Moonshot's flagship Kimi K3 — the highest-quality model on ai&, pairing a 1M context window with vision and document input.",
    specialties: [
      "Top Theozard quality score on the platform (95)",
      "1M context with vision + document input",
      "Frontier reasoning + tool calling for the hardest tasks",
    ],
    limitations: [
      "Most expensive model on ai& ($3.00 / $12.50 per 1M)",
      "No video input (unlike gemma-4 and qwen3.6)",
      "Overkill for routine tasks — cheaper models handle those fine",
    ],
  },
};

// Complexity tiers — how much of each call's input repeats on average.
// ai& caches repeated prefixes automatically (prompts ≥1,024 tokens), so the
// repeat share of a workload is what drives caching savings.
// Shares below are measured against the live API by the benchmark project
// (see https://github.com/SumerSG/aiand-cache-benchmark) — see BENCH_NOTE.
// Shares MEASURED against the live ai& API (Aug 24–25, 2026 — 233 calls,
// 5 models) by https://github.com/SumerSG/aiand-cache-benchmark
const TIERS = {
  low:    { share: 0.06, label: "Low",    blurb: "one-shot tasks — little repeats" },
  medium: { share: 0.71, label: "Medium", blurb: "multi-turn chats — history repeats" },
  high:   { share: 0.78, label: "High",   blurb: "agentic tool loops — every step repeats" },
};
const BENCH_NOTE = "Repeat shares measured on the live ai& API (233 calls, 5 models, Aug 24–25 2026)";

// Quick example presets: per-call token usage + monthly call volume,
// sorted into complexity buckets. sample: file in samples/ for download.
const PRESETS = {
  // low complexity — one-shot calls
  translate:  { label: "Translate a Doc",     tier: "low",    inputTokens: 6_000,  outputTokens: 6_000, callsPerMonth: 200,    sample: "06-translated-release-notes-ja.md" },
  email:      { label: "Email Campaign",      tier: "low",    inputTokens: 600,    outputTokens: 350,   callsPerMonth: 2_000,  sample: "04-email-campaign.eml" },
  content:    { label: "Content Gen",         tier: "low",    inputTokens: 1_500,  outputTokens: 3_000, callsPerMonth: 3_000,  sample: "10-content-gen-blog-post.md" },
  ppt:        { label: "10-Page PPT",         tier: "low",    inputTokens: 2_000,  outputTokens: 3_500, callsPerMonth: 30,     sample: "01-ten-page-ppt.pptx" },
  financial:  { label: "Financial Statement", tier: "low",    inputTokens: 40_000, outputTokens: 1_500, callsPerMonth: 100,    sample: "02-financial-statement.xlsx" },
  // medium complexity — multi-turn chats
  chatbot:    { label: "Chatbot",             tier: "medium", inputTokens: 1_000,  outputTokens: 300,   callsPerMonth: 20_000, sample: "07-chatbot-transcript.json" },
  docs:       { label: "Doc Analysis",        tier: "medium", inputTokens: 30_000, outputTokens: 2_000, callsPerMonth: 1_000,  sample: "09-doc-analysis-summary.txt" },
  contract:   { label: "Contract Review",     tier: "medium", inputTokens: 25_000, outputTokens: 2_000, callsPerMonth: 60,     sample: "05-contract-review.docx" },
  // high complexity — agentic tool loops
  code:       { label: "Code Assistant",      tier: "high",   inputTokens: 5_000,  outputTokens: 1_500, callsPerMonth: 5_000,  sample: "08-code-assistant-example.py" },
  buildapp:   { label: "Build an App",        tier: "high",   inputTokens: 8_000,  outputTokens: 4_000, callsPerMonth: 500,    sample: "03-tip-calculator.html" },
};

// Approximate conversion factors (industry heuristics)
const CHARS_PER_TOKEN = 4;
const WORDS_PER_TOKEN = 0.75;
