// GENERATED by scripts/sync-models.mjs — do not edit by hand
// Source: GET https://api.aiand.com/v1/models (snapshot: 2026-08-24)
const MODELS_LIVE = [
  {
    "id": "deepseek-ai/deepseek-v4-flash",
    "provider": "deepseek-ai",
    "context": 1048576,
    "capabilities": [
      "reasoning",
      "tool_calling"
    ],
    "inputPer1M": 0.15,
    "outputPer1M": 0.25,
    "cachedInputPer1M": 0.08
  },
  {
    "id": "google/gemma-4-31b-it",
    "provider": "google",
    "context": 262144,
    "capabilities": [
      "reasoning",
      "tool_calling",
      "vision",
      "video",
      "document"
    ],
    "inputPer1M": 0.2,
    "outputPer1M": 0.5,
    "cachedInputPer1M": 0.05
  },
  {
    "id": "openai/gpt-oss-120b",
    "provider": "openai",
    "context": 131072,
    "capabilities": [
      "reasoning",
      "tool_calling"
    ],
    "inputPer1M": 0.15,
    "outputPer1M": 0.6,
    "cachedInputPer1M": 0.08
  },
  {
    "id": "motif-technologies/motif-3",
    "provider": "Motif-Technologies",
    "context": 262144,
    "capabilities": [
      "chat",
      "reasoning",
      "tool_calling"
    ],
    "inputPer1M": 0.5,
    "outputPer1M": 2,
    "cachedInputPer1M": 0.2
  },
  {
    "id": "deepseek-ai/deepseek-v4-pro",
    "provider": "deepseek-ai",
    "context": 1048576,
    "capabilities": [
      "reasoning",
      "tool_calling"
    ],
    "inputPer1M": 1,
    "outputPer1M": 2.5,
    "cachedInputPer1M": 0.25
  },
  {
    "id": "qwen/qwen3.6-27b",
    "provider": "qwen",
    "context": 262144,
    "capabilities": [
      "reasoning",
      "tool_calling",
      "vision",
      "video",
      "document"
    ],
    "inputPer1M": 0.32,
    "outputPer1M": 3.2,
    "cachedInputPer1M": 0.2
  },
  {
    "id": "moonshotai/kimi-k2.7-code",
    "provider": "moonshotai",
    "context": 262144,
    "capabilities": [
      "reasoning",
      "tool_calling",
      "vision",
      "document"
    ],
    "inputPer1M": 0.75,
    "outputPer1M": 3.5,
    "cachedInputPer1M": 0.2
  },
  {
    "id": "zai-org/glm-5.2",
    "provider": "zai-org",
    "context": 1048576,
    "capabilities": [
      "reasoning",
      "tool_calling"
    ],
    "inputPer1M": 1,
    "outputPer1M": 4,
    "cachedInputPer1M": 0.3
  },
  {
    "id": "moonshotai/kimi-k3",
    "provider": "moonshotai",
    "context": 1048576,
    "capabilities": [
      "reasoning",
      "tool_calling",
      "vision",
      "document"
    ],
    "inputPer1M": 3,
    "outputPer1M": 12.5,
    "cachedInputPer1M": 0.5
  }
];
