"""Generated by the Code Assistant preset: retry decorator with exponential backoff."""
import functools
import time
import random


def retry_with_backoff(max_attempts=3, base_delay=0.5, max_delay=30.0, exceptions=(Exception,)):
    """Retry the wrapped function with exponential backoff + jitter.

    >>> @retry_with_backoff(max_attempts=5)
    ... def call_api(): ...
    """
    def decorator(func):
        @functools.wraps(func)
        def wrapper(*args, **kwargs):
            for attempt in range(1, max_attempts + 1):
                try:
                    return func(*args, **kwargs)
                except exceptions:
                    if attempt == max_attempts:
                        raise
                    delay = min(base_delay * 2 ** (attempt - 1), max_delay)
                    time.sleep(delay * random.uniform(0.5, 1.5))  # jitter
        return wrapper
    return decorator
