#!/usr/bin/env node
// Sync the live ai& model catalog into models-live.js.
//
// Usage:  node scripts/sync-models.mjs
// Key:    reads $AIAND_API_KEY, falling back to the opencode CLI's stored
//         credential in ~/.local/share/opencode/auth.json
//
// Only models-live.js is touched — editorial content in data.js is never
// overwritten. Re-run anytime, then commit + push to deploy fresh pricing.

import { readFileSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";

const OUT_FILE = new URL("../models-live.js", import.meta.url);

function getApiKey() {
  if (process.env.AIAND_API_KEY) return process.env.AIAND_API_KEY;
  try {
    const auth = JSON.parse(readFileSync(join(homedir(), ".local/share/opencode/auth.json"), "utf8"));
    if (auth?.opencode?.key) return auth.opencode.key;
  } catch {}
  console.error("No API key found. Set AIAND_API_KEY or log in via the opencode CLI.");
  process.exit(1);
}

function previousIds() {
  try {
    const src = readFileSync(OUT_FILE, "utf8");
    return [...src.matchAll(/"id": "([^"]+)"/g)].map((m) => m[1]);
  } catch {
    return [];
  }
}

const res = await fetch("https://api.aiand.com/v1/models", {
  headers: { Authorization: `Bearer ${getApiKey()}` },
});
if (!res.ok) {
  console.error(`API request failed: ${res.status} ${res.statusText}`);
  process.exit(1);
}
const { data } = await res.json();

const models = data
  .map((m) => ({
    id: m.id,
    provider: m.provider,
    context: m.context_window,
    capabilities: m.capabilities ?? [],
    inputPer1M: Number(m.input_per_1m),
    outputPer1M: Number(m.output_per_1m),
    cachedInputPer1M: m.cached_input_per_1m != null ? Number(m.cached_input_per_1m) : null,
  }))
  .sort((a, b) => a.inputPer1M + a.outputPer1M - (b.inputPer1M + b.outputPer1M));

const date = new Date().toISOString().slice(0, 10);
const before = previousIds();
const after = models.map((m) => m.id);

writeFileSync(
  OUT_FILE,
  `// GENERATED by scripts/sync-models.mjs — do not edit by hand\n` +
    `// Source: GET https://api.aiand.com/v1/models (snapshot: ${date})\n` +
    `const MODELS_LIVE = ${JSON.stringify(models, null, 2)};\n`
);

console.log(`models-live.js updated — ${models.length} models (snapshot ${date})`);
for (const id of after.filter((x) => !before.includes(x))) console.log(`  + added:   ${id}`);
for (const id of before.filter((x) => !after.includes(x))) console.log(`  - removed: ${id}`);
if (before.length && before.every((x) => after.includes(x)) && after.every((x) => before.includes(x)))
  console.log("  (no model additions or removals — prices/context refreshed)");
